version: '2.3'

services:

  superstream-server:
    # environment:
    #   - CONFIG_PROP=config-mysql.properties
    image: superstream-server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080 
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
    #   mysql:
    #     condition: service_healthy
    # volumes:
    #   - ../server/config:/app/config
    #   - ./logs:/app/logs
 
  redis:
    image: "redis:alpine"
    # environment:
    #   - WF_SERVER=http://conductor-server:8080/api/  
    networks:
      - internal
    ports:
      - 6379:6379
    # ports:
    #   - '127.0.0.1:6379:6379/tcp'
    # expose:
    #   - 6379
    # healthcheck:
    #   test: ["CMD", "redis-cli","ping"]
    healthcheck:
      test: redis-cli ping
      interval: 3s
      timeout: 5s
      retries: 5
    # depends_on:
    #   - conductor-server
 
# volumes:
#   conductor_mysql:

networks:
  internal:
